# Spring Core
spring:
  application:
    name: java 10 with spring-boot 2.1
  #OUTPUT
  output:
    ansi:
      enabled: detect
  #PROFILES
  profiles:
    active: dev
  #DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true
    username: demo_user
    password: demo_pass
    hikari:
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 2
  #JPA
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  #JACKSON
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true

#EMBEDDED SERVER CONFIGURATION
server:
  servlet:
    context-path: /app
  port: 9000

#LOGGING
logging.file: demo.log
logging:
  file:
    max-size: 50MB
    max-history: 10
  level:
    root: info
    org.springframework: info
    org.hibernate: info
    org.hibernate.SQL: debug
    com.example.demo: debug
