# Spring Core
spring:
  application:
    name: java 11 with spring-boot 2.1
  #OUTPUT
  output:
    ansi:
      enabled: detect
  #PROFILES
  profiles:
    active: dev
  #DATASOURCE
  datasource:
    url: jdbc:mysql://localhost:3306/demo_db?useSSL=false&allowPublicKeyRetrieval=true
    username: demo_user
    password: demo_pass
    hikari:
      connection-test-query: select 1
      connection-timeout: 10000
      maximum-pool-size: 2
      minimum-idle: 2
  data:
    jpa:
      repositories:
        enabled: true
        bootstrap-mode: lazy
  #JPA
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        generate_statistics: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  #JACKSON
  jackson:
    serialization:
      indent-output: true
      write-dates-as-timestamps: false
      write-durations-as-timestamps: true
  #DEVTOOLS
  devtools:
    livereload:
      enabled: false
  #INSIGHTS
  http:
    log-request-details: true

#EMBEDDED SERVER CONFIGURATION
server:
  servlet:
    context-path: /app
  port: 9000
  error:
    whitelabel:
      enabled: true
  tomcat:
    max-swallow-size: 2MB

#LOGGING
#logging.file: log/demo.log
#logging:
#  file:
#    max-size: 50MB
#    max-history: 10
#  level:
#    root: info
#    org.springframework: info
#    org.hibernate: info
#    org.hibernate.SQL: debug
#    com.example.demo: debug

---

spring:
  profiles: dev & app1
server:
  port: 9001

---

spring:
  profiles: dev & app2
server:
  port: 9002
